audio_model:
  feature_dim: 1024
  frameshift: 10
  max_length: 1024
  model_type: audiomae
  n_mels: 128
  pretrained_path: pretrained/audiomae_base.pth
  sample_rate: 32000
llm:
  model_name_or_path: Qwen/QwQ-32B
  model_type: auto
